package mocks

import "github.com/plimble/micro"
import "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Client) Close() {
	_m.Called()
}

// Publish provides a mock function with given fields: subject, v, opts
func (_m *Client) Publish(subject string, v interface{}, opts ...micro.ClientOption) error {
	ret := _m.Called(subject, v, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, ...micro.ClientOption) error); ok {
		r0 = rf(subject, v, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Request provides a mock function with given fields: subject, req, res, opts
func (_m *Client) Request(subject string, req interface{}, res interface{}, opts ...micro.ClientOption) error {
	ret := _m.Called(subject, req, res, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, interface{}, ...micro.ClientOption) error); ok {
		r0 = rf(subject, req, res, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
