// Code generated by protoc-gen-go.
// source: github.com/plimble/micro/example/proto/hello.proto
// DO NOT EDIT!

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	github.com/plimble/micro/example/proto/hello.proto

It has these top-level messages:
	HelloReq
	HelloRes
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" gorethink:"name"`
}

func (m *HelloReq) Reset()                    { *m = HelloReq{} }
func (m *HelloReq) String() string            { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()               {}
func (*HelloReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloRes struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty" gorethink:"result"`
}

func (m *HelloRes) Reset()                    { *m = HelloRes{} }
func (m *HelloRes) String() string            { return proto.CompactTextString(m) }
func (*HelloRes) ProtoMessage()               {}
func (*HelloRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*HelloReq)(nil), "HelloReq")
	proto.RegisterType((*HelloRes)(nil), "HelloRes")
}

func init() { proto.RegisterFile("github.com/plimble/micro/example/proto/hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0xc8, 0xc9, 0xcc, 0x4d, 0xca, 0x49, 0xd5, 0xcf,
	0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0x00, 0xf2, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0xf5, 0x33, 0x52, 0x73, 0x72, 0xf2, 0xf5, 0xc0, 0x6c, 0x25, 0x39, 0x2e, 0x0e, 0x0f, 0x10,
	0x37, 0x28, 0xb5, 0x50, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x56, 0x52, 0x82, 0xcb, 0x17, 0x0b, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0x16,
	0x97, 0xe6, 0x94, 0x40, 0x55, 0x40, 0x79, 0x49, 0x6c, 0x60, 0xa3, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xcf, 0x19, 0x1e, 0xab, 0x80, 0x00, 0x00, 0x00,
}
